version: '3'

services:
  auth-rabbitmq:
    hostname: "auth-rabbitmq"
    container_name: "auth-rabbitmq"
    image: "bitnami/rabbitmq:latest"
    env_file:
      - auth-rabbitmq.env
    networks:
      - auth-network
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - "auth_rabbitmq_data:/bitnami"

  auth-redis:
    hostname: "auth-redis"
    container_name: "auth-redis"
    image: "bitnami/redis:5.0.4"
    env_file:
      - auth-redis.env
    networks:
      - auth-network
    ports:
      - "6379:6379"
    volumes:
      - "auth_redis_data:/bitnami/redis/data"

  auth:
    build:
      context: ./auth_app
      dockerfile: Dockerfile
    container_name: Authentication
    command: 'bash -c "uvicorn auth_app.main:auth_app --host 0.0.0.0 --port 7003 --log-config=auth_app/logging.conf --reload"'
    volumes:
      - '.:/auth_app'
    ports:
      - '7003:7003'
    env_file: auth_app/.env
    networks:
      - auth-network
    restart: on-failure
#    depends_on:
#      - mongodb_auth

  auth-celery-flower:
    container_name: "auth-celery-flower"
    image: gregsi/latest-celery-flower-docker:latest
    env_file:
      - auth-celery-flower.env
    ports:
      - "5556:5555"
    depends_on:
      - auth-rabbitmq
      - auth-redis
    networks:
      - auth-network
  email-worker:
    hostname: "email-worker"
    container_name: "email-worker"
    build:
      context: ./auth_app
      dockerfile: Dockerfile
    command: "celery -A auth_app.utils.tasks.celery worker --loglevel=info --logfile=auth_app/logs/email_worker.log -Q send_verify_email,send_change_password_email"
    env_file: email-worker.env
    volumes:
      - '.:/auth_app'
    links:
      - auth-rabbitmq
    depends_on:
      - auth-rabbitmq
      - auth-redis
    networks:
      - auth-network

#  mongodb_auth:
##    image: mongo:latest
#    container_name: mongodb_auth
#    image: bitnami/mongodb:latest
#    ports:
#      - "27017:27017"
#    volumes:
#      - data:/bitnami/mongodb
#    networks:
#      - auth-network
volumes:
  data:
  auth_rabbitmq_data:
    driver: local
  auth_redis_data:
    driver: local
networks:
  auth-network:
    driver: bridge